version: "3.9"
services:
  web:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    volumes:
      - type: bind
        source: ./java-plugin/target/java-plugin-1.0.0-SNAPSHOT.jar
        target: /opt/sonarqube/extensions/plugins/java-plugin-1.0.0-SNAPSHOT.jar
      - type: bind
        source: ./php-plugin/target/php-plugin-1.0.0-SNAPSHOT.jar
        target: /opt/sonarqube/extensions/plugins/php-plugin-1.0.0-SNAPSHOT.jar
      - type: bind
        source: ./python-plugin/target/python-plugin-1.0.0-SNAPSHOT.jar
        target: /opt/sonarqube/extensions/plugins/python-plugin-1.0.0-SNAPSHOT.jar
